#index:
#    path: /
#    controller: App\Controller\DefaultController::index
vkontakte_login:
    path: /login/check-vkontakte
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
    prefix:   /login
logout:
    path: /logout
login:
    path: /login